<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>cf528149-6e1c-44c9-8a7a-cf87864b69f5</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MiniErp.Application\MiniErp.Application.csproj" />
    <ProjectReference Include="..\MiniErp.Domain\MiniErp.Domain.csproj" />
    <ProjectReference Include="..\MiniErp.Persistence.EfCore\MiniErp.Persistence.EfCore.csproj" />
  </ItemGroup>

</Project>
