using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace MiniErp.Persistence.EfCore.Customers;

internal sealed class CustomerConfiguration : IEntityTypeConfiguration<CustomerRecord>
{
    public void Configure(EntityTypeBuilder<CustomerRecord> builder)
    {
        builder.ToTable("customers");

        builder.HasKey(customer => customer.Id);

        // The id is generated by the domain (Guid v7), never by the database. The column type of the
        // Guid is left to the provider.
        builder.Property(customer => customer.Id)
            .HasColumnName("id")
            .ValueGeneratedNever();

        builder.Property(customer => customer.LegalName)
            .HasColumnName("legal_name")
            .HasMaxLength(200)
            .IsRequired();

        builder.Property(customer => customer.TaxId)
            .HasColumnName("tax_id")
            .HasMaxLength(11)
            .IsRequired();

        // Stored as text so that reordering the enum never corrupts data.
        builder.Property(customer => customer.VatCondition)
            .HasColumnName("vat_condition")
            .HasMaxLength(30)
            .IsRequired();

        builder.Property(customer => customer.Email)
            .HasColumnName("email")
            .HasMaxLength(254);

        builder.Property(customer => customer.Phone)
            .HasColumnName("phone")
            .HasMaxLength(30);

        builder.Property(customer => customer.Address)
            .HasColumnName("address")
            .HasMaxLength(300);

        builder.HasIndex(customer => customer.TaxId)
            .IsUnique()
            .HasDatabaseName("ux_customers_tax_id");

        builder.HasIndex(customer => customer.LegalName)
            .HasDatabaseName("ix_customers_legal_name");
    }
}
